name: Scheduled API Calls - every 40m

on:
  push:
    branches: [ main ]

  pull_request:    
    branches: [ main ]

  # Schedules the workflow to run every 40 minutes
  schedule:
    - cron: '*/40 * * * *'
  
jobs:
  callApi:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          curl -I https://newsapi-msrnow.vercel.app/api/scrape/triggers/secondary-news-categories?from=github-action&every=40m
           if [[ $? -eq 0 ]]; then
            echo "API call was successful"
          else
            echo "API call failed"
            exit 1
          fi
