name: Scheduled API Calls

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API Endpoint
        run: |
          curl -I https://newsapi-msrnow.vercel.app/api/scrape/trigger-all?github-action
